ALTER TABLE IDN_OAUTH2_DEVICE_FLOW ADD COLUMN SUBJECT_IDENTIFIER VARCHAR(255);
INSERT INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES ('7f24050f-3e3d-4a00-b10f-fd5450d6523e', 'input-validation-configurations', 'A resource type to store input validation related configurations');
ALTER TABLE SP_SHARED_APP ADD COLUMN SHARE_WITH_ALL_CHILDREN BOOLEAN DEFAULT FALSE;